url: "https://gbrl-mendes.github.io"
baseurl: ""
title: Gabriel Mendes
logo: "/images/logo.png?raw=true"

description: >
  <br><br>
  +7 years of Bioinformatics and Data Analysis. Possess Master's in Genetics and Biotecnolgy from UFMG, I employ data analysis and visualization tools in eDNA metabarcoding research.<br>
  <br>
  My expertise centers on handling large datasets and conducting statistical analyses using R, with a focus on data visualization and reproducibility. I combine molecular biology's scientific rigor with modern computational tools—including Linux, Shell Script, SQL, Git, and Cloud Computing—to transform raw data into clear biological insights.<br>
  <br><br>
  <a href="https://www.linkedin.com/in/gabriel-mendes-b2b4432ba/">View My LinkedIn Profile</a>
  <br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0
