url: "https://gbrl-mendes.github.io"
baseurl: ""
title: Gabriel Mendes, Msc
logo: "./images/logo.png?raw=true"

description: >
  <br>
  +7 years of Bioinformatics and Data Analysis experience. Possess Master's in Genetics with emphasis on Bioinformatics and Genomics from UFMG, I employ data analysis and visualization tools in eDNA metabarcoding research.
  <br><br>
  My expertise centers on handling large datasets and conducting statistical analyses using R, with a focus on data visualization and reproducibility. I combine molecular biology's scientific rigor with modern computational tools—including Linux, Shell Script, SQL, Git, and Cloud Computing—to transform raw data into clear biological insights.
  <br>
  <div style="line-height: 1.8;">
  <a href="https://www.linkedin.com/in/gabriel-mendes-b2b4432ba/">LinkedIn Profile</a><br>
  <a href="http://lattes.cnpq.br/8573247637516819">Lattes CV</a><br>
  <a href="https://orcid.org/0000-0002-1260-5993">Orcid Profile</a>
  </div>

  <br><br><br><br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0